### ISSUE TITLE
Missing glyph with psefiston in Main font

### ISSUE THREAD

**Issue by ilizol** [t-bullock/KA-Old-Style#4]
font: KAAlmouziosMain-Regular.ttf

name: B
unicode: 0042

**Comment by t-bullock** [comment]
This is by design. Almouzios doesn't have two different sized oliga like KA-New-Stathis does, so a long psefeston ('B') is not needed.

**Comment by ilizol** [comment]
Maybe we must have the same glyph with "n" (psefiston), because when we will use this font in Kassia there will be incompatibility with other KA fonts.

**Comment by t-bullock** [comment]
I don't think we'll have compatibility issues. I don't think the extra long psefeston will be a standard neume specified in BNML.  Rather, we'll have something like
`<neumes>oligon_isonUL_ken2UR psefestonD</neumes>` and Kassia will check Almouzios, special information in the Almouzios font config, and grab the appropriate psefeston from the Almouzios font.
