### ISSUE TITLE
Nine voices down is wrong in Main font

### ISSUE THREAD

**Issue by ilizol** [t-bullock/KA-Old-Style#5]
font: KAAlmouziosMain-Regular.ttf

name: parenleft
unicode: 0028

![Screenshot_20200516_161050](https://user-images.githubusercontent.com/7188298/82120575-dc475000-978f-11ea-9220-98967863b7aa.png)

**Comment by t-bullock** [comment]
This should be fixed now with https://github.com/t-bullock/KA-Almouzios/commit/0d73e3446a8154867d3ca7f3d3847d590be44b28.
